apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mlflow
  namespace: infra-tools
spec:
  project: default
  source:
    repoURL: https://community-charts.github.io/helm-charts
    chart: mlflow
    targetRevision: 1.6.2
    helm:
      releaseName: mlflow
      values:
        service:
          type: ClusterIP
          port: 5000
        auth:
          enabled: false
        postgresql:
          enabled: false
        extraEnvVars:
          AWS_ACCESS_KEY_ID: "minio"
          AWS_SECRET_ACCESS_KEY: "minio123"
          MLFLOW_S3_ENDPOINT_URL: "http://minio.infra-tools.svc.cluster.local:9000"
          MLFLOW_BACKEND_STORE_URI: "postgresql://mlflow:mlflowpass@mlflow-postgres.infra-tools.svc.cluster.local:5432/mlflow"
          MLFLOW_ARTIFACT_ROOT: "s3://mlflow-artifacts"
        extraArgs:
          backend-store-uri: "$(MLFLOW_BACKEND_STORE_URI)"
          default-artifact-root: "$(MLFLOW_ARTIFACT_ROOT)"
          host: "0.0.0.0"
          port: "5000"
  destination:
    server: https://kubernetes.default.svc
    namespace: infra-tools
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true


