apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pushgateway
  namespace: infra-tools  # namespace ArgoCD Application
spec:
  project: default
  source:
    repoURL: https://prometheus-community.github.io/helm-charts
    chart: prometheus-pushgateway
    targetRevision: 2.7.0
    helm:
      releaseName: pushgateway
      valuesObject:
        service:
          type: ClusterIP
          port: 9091
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring  # namespace для PushGateway
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ServerSideApply=true
      - SkipDryRunOnMissingResource=true



